# Generated by Django 6.1.1 on 2026-09-18 08:48

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
